#! /bin/sh

xrdb -load ~/.config/xterm/xresources
xsetroot -cursor_name left_ptr

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 一 二 三 四 五 六 七 八 九

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config window_gap 5
bspc config top_padding 1
bspc config bottom_padding 1
bspc config left_padding 1
bspc config right_padding 1

bspc config normal_border_color  "#bd93f9" 
bspc config focused_border_color "#50fa7b"
#bspc config pointer_follows_monitor true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --bg-scale ~/.config/wallpapers/wallpaper-debian-dragon.png
polybar &

